In [1]:
import numpy as np
import pandas as pd

## Exercise 1. Series

We have the following two lists, the first one contains the names of a group of people, and the second contains their ages

In [2]:
names = ['John', 'Mary', 'Carl', 'Michael', 'Jones']
ages = [25, 32, 41, 29, 36]

Create a Series of the ages, indexed by the names

In [4]:
# write your code here
s=pd.Series(ages, index = names)
s

John       25
Mary       32
Carl       41
Michael    29
Jones      36
dtype: int64

What is the age of Mary?

In [5]:
# write your code here
s['Mary']

32

Select the ages of Mary, Carl and Jones

In [10]:
# write your code here
s1 = s[['Mary','Carl','Jones']]
s1

Mary     32
Carl     41
Jones    36
dtype: int64

What is the average of those ages? (use `np.average` or `.mean()` )

In [11]:
# write your code here
average_age = np.average(s1)
average_age

36.333333333333336

In [12]:
# write your code here
s1.mean()

36.333333333333336

Select the ages from the 3rd element on .. (i.e., from pos=2 till the last)

In [13]:
# write your code here
s[2:]

Carl       41
Michael    29
Jones      36
dtype: int64

Get the descriptive statistics of the Series

In [14]:
# write your code here
s.describe()

count     5.000000
mean     32.600000
std       6.188699
min      25.000000
25%      29.000000
50%      32.000000
75%      36.000000
max      41.000000
dtype: float64

## Exercise 2. DataFrame

In a store, there are many items..
* Each item has a name, a **type**, a **color**, and the **quantity** of each item
* These informations are organized as a list of tuples
* i.e., each tuple represents an item, e.g., `('S-56', 'A', 'Red', 234)`

In [ ]:
data = [('S-56', 'A', 'Red',    234), ('S-57', 'A', 'Blue',   432),
        ('S-58', 'A', 'Orange', 902), ('S-59', 'A', 'Red',    340),
        ('S-60', 'B', 'Yellow', 253), ('S-61', 'B', 'Red',    232), 
        ('S-62', 'C', 'Green', 1042), ('S-63', 'C', 'Red',   1204),
        ('S-64', 'B', 'Yellow', 432), ('S-65', 'C', 'Green',  985)]

In [ ]:
columns = ['item_id','type','color','quantity']
df = pd.DataFrame(data,columns =columns)
df

  item_id type   color  quantity
0    S-56    A     Red       234
1    S-57    A    Blue       432
2    S-58    A  Orange       902
3    S-59    A     Red       340
4    S-60    B  Yellow       253
5    S-61    B     Red       232
6    S-62    C   Green      1042
7    S-63    C     Red      1204
8    S-64    B  Yellow       432
9    S-65    C   Green       985

Create a DataFrame from this list, and name the columns: item_id, type, color, quantity

In [ ]:
# write your code here

  item_id type   color  quantity
0    S-56    A     Red       234
1    S-57    A    Blue       432
2    S-58    A  Orange       902
3    S-59    A     Red       340
4    S-60    B  Yellow       253
5    S-61    B     Red       232
6    S-62    C   Green      1042
7    S-63    C     Red      1204
8    S-64    B  Yellow       432
9    S-65    C   Green       985

What is the shape of the DataFrame?

In [ ]:
shape = df.shape
shape

(10, 4)

In [ ]:
# write your code here

(10, 4)

Show the head of the DataFrame

In [ ]:
head = df.head()
head

  item_id type   color  quantity
0    S-56    A     Red       234
1    S-57    A    Blue       432
2    S-58    A  Orange       902
3    S-59    A     Red       340
4    S-60    B  Yellow       253

In [ ]:
# write your code here

Show the tail of the DataFrame

In [ ]:
tail = df.tail()
tail

  item_id type   color  quantity
5    S-61    B     Red       232
6    S-62    C   Green      1042
7    S-63    C     Red      1204
8    S-64    B  Yellow       432
9    S-65    C   Green       985

In [ ]:
# write your code here

  item_id type   color  quantity
5    S-61    B     Red       232
6    S-62    C   Green      1042
7    S-63    C     Red      1204
8    S-64    B  Yellow       432
9    S-65    C   Green       985

Show the info of the DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   10 non-null     object
 1   type      10 non-null     object
 2   color     10 non-null     object
 3   quantity  10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes

In [ ]:
# write your code here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   10 non-null     object
 1   type      10 non-null     object
 2   color     10 non-null     object
 3   quantity  10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes

Show the columns of the DataFrame

In [ ]:
df.columns

Index(['item_id', 'type', 'color', 'quantity'], dtype='object')

In [ ]:
# write your code here

Index(['item_id', 'type', 'color', 'quantity'], dtype='object')

Convert the datatype of `quantity` column to float

In [ ]:
# df=df.astype({'quantity':float})
df['quantity'].astype('float')
df

  item_id type   color  quantity
0    S-56    A     Red     234.0
1    S-57    A    Blue     432.0
2    S-58    A  Orange     902.0
3    S-59    A     Red     340.0
4    S-60    B  Yellow     253.0
5    S-61    B     Red     232.0
6    S-62    C   Green    1042.0
7    S-63    C     Red    1204.0
8    S-64    B  Yellow     432.0
9    S-65    C   Green     985.0

In [ ]:
df['quantity'].dtypes

dtype('float64')

In [ ]:
# write your code here

  item_id type   color  quantity
0    S-56    A     Red     234.0
1    S-57    A    Blue     432.0
2    S-58    A  Orange     902.0
3    S-59    A     Red     340.0
4    S-60    B  Yellow     253.0
5    S-61    B     Red     232.0
6    S-62    C   Green    1042.0
7    S-63    C     Red    1204.0
8    S-64    B  Yellow     432.0
9    S-65    C   Green     985.0

## Exercise 3. DataFrame

Create a numpy array of random integers between 200 and 300, with size (20, 3)

In [15]:
arr = np.random.randint(200, 301, size=(20,3))
arr

array([[223, 276, 212],
       [274, 245, 241],
       [216, 201, 242],
       [215, 243, 257],
       [300, 300, 213],
       [208, 294, 262],
       [267, 294, 292],
       [232, 238, 300],
       [252, 298, 228],
       [261, 207, 233],
       [285, 265, 290],
       [293, 212, 263],
       [267, 257, 225],
       [264, 300, 236],
       [249, 205, 260],
       [210, 227, 273],
       [284, 220, 206],
       [296, 257, 237],
       [286, 249, 256],
       [228, 265, 208]])

Create a DataFrame from the previous array, and name the columns A, B and C.
Then print its shape, and show its head

In [16]:
df = pd.DataFrame(arr, columns=['A','B','C'])
print(df.shape)
df.head()

(20, 3)

     A    B    C
0  223  276  212
1  274  245  241
2  216  201  242
3  215  243  257
4  300  300  213

Repeat the previous question (with the same array), but this time use as index the numbers from 25 to 45

In [17]:
df = pd.DataFrame(arr, columns=['A','B','C'], index=np.arange(25,45))
print(df.shape)
df.head()

(20, 3)

      A    B    C
25  223  276  212
26  274  245  241
27  216  201  242
28  215  243  257
29  300  300  213

Rename the column A to Q, and column C to Z. (show the head to see the changes)

In [18]:
df.columns = ['Q','B','Z']

In [19]:
df.rename(columns={'A':'Q', 'C':'Z'}, inplace=True)
df

      Q    B    Z
25  223  276  212
26  274  245  241
27  216  201  242
28  215  243  257
29  300  300  213
30  208  294  262
31  267  294  292
32  232  238  300
33  252  298  228
34  261  207  233
35  285  265  290
36  293  212  263
37  267  257  225
38  264  300  236
39  249  205  260
40  210  227  273
41  284  220  206
42  296  257  237
43  286  249  256
44  228  265  208

Make a numpy array out of the DataFrame. 
Then, reshape that array into (12,5), and create a new DataFrame out of it with column names U,V,W,X,Y

In [20]:
a = df.to_numpy()
print(a.shape)
a = a.reshape(12, 5)
df2 = pd.DataFrame(a, columns=['U','V','W','X','Y'])
print(df2.shape)
df2.head()

(20, 3)
(12, 5)

     U    V    W    X    Y
0  223  276  212  274  245
1  241  216  201  242  215
2  243  257  300  300  213
3  208  294  262  267  294
4  292  232  238  300  252

Save the DataFrame into a csv file (named `my12x5df.csv`) (excluding the index)

In [21]:
df2.to_csv('my12x5df.csv', index=False)

## Exercise 4. DataFrame

**Question 1**. Read the csv file `sales.csv` into a DataFrame.
Then, print its shape, and show its head

In [24]:
# write your code here
df = pd.read_csv('sales.csv')
print(df.shape)
df.head()

(100, 5)

     ID  product  quantity  month  year
0  s001   Tablet        60      1  2019
1  s002  Headset        77      1  2019
2  s003   Tablet        40      1  2019
3  s004  Headset        38      2  2019
4  s005  Printer        72      2  2019

**Question 2**. Repeat Question 1 (read the csv file `sales.csv` into a DataFrame), but use the first column `ID` as index.
Then, print the shape, and show all the dataframe

In [30]:
# write your code here
df = pd.read_csv('sales.csv', index_col= ['ID'])
print(df.shape)
df.head()

(100, 4)

      product  quantity  month  year
ID
s001   Tablet        60      1  2019
s002  Headset        77      1  2019
s003   Tablet        40      1  2019
s004  Headset        38      2  2019
s005  Printer        72      2  2019

**Question 3**. Repeat Question 1 (read the csv file `sales.csv` into a DataFrame), 
but read only the columns `quantity`, `month` and `year`, and only the first 20 rows.
Then, print the shape, and show the head

In [31]:
# write your code here
df = pd.read_csv('sales.csv', usecols= ['quantity','month','year'],nrows=20)
print(df.shape)
df.head()

(20, 3)

   quantity  month  year
0        60      1  2019
1        77      1  2019
2        40      1  2019
3        38      2  2019
4        72      2  2019

Save the previous dataframe into a csv file (named `sales2.tsv`) using tab (`\t`) as separator, exclude the index, and exclude the header (column names)

In [33]:
# write your code here
df.to_csv('sales2.tsv',sep = '\t',index = False, header = False)

(You may try to open the file using Excel or Google-sheets to check it. Remeber that it is tab-separated, and there are no column names)

Read the last file `sales2.tsv` into a DataFrame, remember that the separator was tab, and there was no header (column names).

In [38]:
# write your code here
df2 = pd.read_csv('sales2.tsv',sep='\t',header = None)
print(df2.shape)
df2.head()

(20, 3)

    0  1     2
0  60  1  2019
1  77  1  2019
2  40  1  2019
3  38  2  2019
4  72  2  2019

Have you noticed what the column names are? 
Now, let the column names be `Qty`, `Month`, and `Year`

In [39]:
# write your code here
df2.columns = ['Qty','Month','Year']
df2.head()

   Qty  Month  Year
0   60      1  2019
1   77      1  2019
2   40      1  2019
3   38      2  2019
4   72      2  2019

In [ ]:
import pandas as pd
df = pd.DataFrame([[2,'3'],[4,'5'],[6,'7']],columns =['a','b'])
df

   a  b
0  2  3
1  4  5
2  6  7

In [ ]:
df.dtypes

a     int64
b    object
dtype: object